services:
  - type: web
    name: mentminds-api
    env: python
    runtime: python
    pythonVersion: "3.11.8"
    rootDir: backend 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mentminds-db
          property: connectionString
      - key: MODEL_PATH
        value: model/mentor_matching_modelv2.pkl
      - key: FEATURE_COLS_PATH
        value: model/feature_columnsv2.pkl
      - key: TFIDF_PATH
        value: model/tfidf_vectorizerv2.pkl
      - key: SBERT_VECS_PATH
        value: model/mentor_sbert_vecsv2.pkl

databases:
  - name: mentminds-db
    databaseName: mentminds
    user: mentminds_user
    plan: free
